blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/YourWisemaker/langchain-laravel/tree/main/docs
    about: Check our comprehensive documentation for usage guides and examples
  - name: 💬 GitHub Discussions
    url: https://github.com/YourWisemaker/langchain-laravel/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/YourWisemaker/langchain-laravel/security/advisories/new
    about: Report security vulnerabilities privately